# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null=True)),
                ('begindate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
    ]
